import { Inter } from 'next/font/google'
import Header from '../../components/Header'
import { AuthModeProvider } from './AuthModeContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Application',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
        <Header />
        {children}
    </div>
  )
}